#!/usr/bin/env node
/**
 * JERRYBAY — deterministic content-board generator for /insights/.
 *
 * No CMS, no backend, no framework. Reads content/posts/*.md (lightweight
 * frontmatter + optional Markdown-lite body), and writes:
 *   - insights/index.html            (category board, newest first)
 *   - insights/<slug>/index.html     (one per post that has body content)
 *
 * External-only posts (external_url, no body) do not get a detail page —
 * their card in the index links straight out.
 *
 * Run from the repo root:
 *   node scripts/content/build-content.mjs
 *
 * This file and every insights/**\/index.html it writes are GENERATED.
 * Edit content/posts/*.md and rerun this script instead of hand-editing
 * the generated HTML.
 */

import { readFileSync, writeFileSync, mkdirSync, readdirSync, rmSync, existsSync } from "node:fs";
import { join, dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..", "..");
const POSTS_DIR = join(ROOT, "content", "posts");
const INSIGHTS_DIR = join(ROOT, "insights");
const GENERATED_MARK = "<!-- GENERATED by scripts/content/build-content.mjs — do not hand-edit; edit content/posts/*.md and rerun. -->";

// Canonical taxonomy — order controls filter button order. A category only
// gets a filter button in the rendered board when it has >=1 post, so an
// unpopulated category never produces a dead filter.
const CATEGORIES = ["AI 활용", "업무 자동화", "노코드 제작", "사업·기획", "강의·자료", "빌드 노트"];

const NAV = [
  ["/resume/", "소개·이력"],
  ["/work/", "프로젝트"],
  ["/lab/", "직접 만든 것"],
  ["/insights/", "콘텐츠"],
  ["/books/", "전자책"],
  ["/contact/", "문의"],
];

function escapeHtml(s) {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

/** Very small Markdown-lite: paragraphs, **bold**, [text](url). No HTML passthrough. */
function renderBody(raw) {
  const paragraphs = raw
    .trim()
    .split(/\n\s*\n/)
    .map((p) => p.trim())
    .filter(Boolean);
  return paragraphs
    .map((p) => {
      let escaped = escapeHtml(p);
      escaped = escaped.replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>");
      escaped = escaped.replace(/\[([^\]]+)\]\(([^)]+)\)/g, (_, text, url) => {
        const external = /^https?:\/\//.test(url);
        return external
          ? `<a href="${url}" target="_blank" rel="noopener noreferrer">${text}</a>`
          : `<a href="${url}">${text}</a>`;
      });
      return `        <p>${escaped}</p>`;
    })
    .join("\n");
}

/** Hand-rolled frontmatter parser: `---\nkey: "value"\n---\nbody`. No YAML dependency. */
function parsePost(fileText, filename) {
  const match = fileText.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n?([\s\S]*)$/);
  if (!match) throw new Error(`${filename}: missing frontmatter block`);
  const [, fm, body] = match;
  const data = {};
  for (const line of fm.split(/\r?\n/)) {
    if (!line.trim()) continue;
    const m = line.match(/^([a-zA-Z_]+):\s*(.*)$/);
    if (!m) continue;
    let [, key, value] = m;
    value = value.trim();
    if (/^".*"$/.test(value)) value = value.slice(1, -1);
    else if (value === "true") value = true;
    else if (value === "false") value = false;
    data[key] = value;
  }
  const required = ["title", "date", "category", "summary"];
  const missing = required.filter((k) => !data[k]);
  if (missing.length) throw new Error(`${filename}: missing frontmatter field(s): ${missing.join(", ")}`);
  if (!CATEGORIES.includes(data.category)) {
    throw new Error(`${filename}: category "${data.category}" is not in the canonical taxonomy (${CATEGORIES.join(", ")})`);
  }
  data.slug = data.slug || filename.replace(/\.md$/, "");
  data.body = body.trim();
  data.hasDetail = data.body.length > 0;
  if (!data.hasDetail && !data.external_url) {
    throw new Error(`${filename}: post has neither body content nor external_url — nothing to link to`);
  }
  return data;
}

function loadPosts() {
  if (!existsSync(POSTS_DIR)) return [];
  return readdirSync(POSTS_DIR)
    .filter((f) => f.endsWith(".md"))
    .map((f) => parsePost(readFileSync(join(POSTS_DIR, f), "utf8"), f))
    .sort((a, b) => (a.date < b.date ? 1 : a.date > b.date ? -1 : 0));
}

function navHtml(current) {
  return NAV.map(([href, label]) =>
    href === current ? `<a href="${href}" aria-current="page">${label}</a>` : `<a href="${href}">${label}</a>`
  ).join("\n      ");
}

function pageShell({ title, description, current, body }) {
  return `<!DOCTYPE html>
<html lang="ko">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${title}</title>
<meta name="description" content="${description}">
<link rel="icon" type="image/svg+xml" href="/assets/favicon.svg">
<link rel="stylesheet" href="/assets/css/site.css">
<meta property="og:type" content="website">
<meta property="og:title" content="${title}">
<meta property="og:description" content="${description}">
<meta property="og:image" content="/assets/profile.jpg">
</head>
<body>
${GENERATED_MARK}
<a class="skip-link" href="#main">본문 바로가기</a>

<header class="site-header">
  <div class="wrap site-header__inner">
    <a class="brand" href="/">JERRY<em>BAY</em></a>
    <button class="nav-toggle" type="button" data-nav-toggle aria-expanded="false" aria-controls="primary-nav">메뉴</button>
    <nav class="nav" id="primary-nav" aria-label="주 메뉴">
      ${navHtml(current)}
    </nav>
  </div>
</header>

<main id="main">
${body}
</main>

<footer class="site-footer">
  <div class="wrap">
    <div class="site-footer__grid">
      <div>
        <p><strong>JERRYBAY</strong> · 배제협의 개인 홈페이지</p>
        <p class="dim">JERRYBAY는 개인 역량 브랜드이며, 기업 계약·청구·납품은 ㈜글로보더를 통해 이루어집니다.</p>
      </div>
      <nav aria-label="푸터 메뉴">
        <a href="/">홈</a>
        <a href="/resume/">소개·이력</a>
        <a href="/work/">프로젝트</a>
        <a href="/lab/">직접 만든 것</a>
        <a href="/insights/">콘텐츠</a>
        <a href="/books/">전자책</a>
        <a href="/contact/">문의</a>
        <a href="/privacy/">개인정보처리방침</a>
      </nav>
    </div>
  </div>
</footer>

<script src="/assets/js/site.js"></script>
</body>
</html>
`;
}

function formatDate(d) {
  const [y, m, day] = d.split("-");
  return `${y}.${m}.${day}`;
}

function renderCard(post) {
  const href = post.hasDetail ? `/insights/${post.slug}/` : post.external_url;
  const targetAttrs = post.hasDetail ? "" : ` target="_blank" rel="noopener noreferrer"`;
  const arrow = post.hasDetail ? "" : ' <span aria-hidden="true">↗</span>';
  return `        <article class="card content-card" data-category="${escapeHtml(post.category)}">
          <div class="chip-row"><span class="chip chip--pending">${escapeHtml(post.category)}</span></div>
          <h3><a href="${href}"${targetAttrs}>${escapeHtml(post.title)}${arrow}</a></h3>
          <p>${escapeHtml(post.summary)}</p>
          <p class="dim">${formatDate(post.date)}</p>
        </article>`;
}

function buildIndex(posts) {
  const populated = CATEGORIES.filter((c) => posts.some((p) => p.category === c));
  const filterButtons = [
    `<button type="button" class="content-filter__btn is-active" data-filter="전체">전체</button>`,
    ...populated.map((c) => `<button type="button" class="content-filter__btn" data-filter="${escapeHtml(c)}">${escapeHtml(c)}</button>`),
  ].join("\n        ");

  const cards = posts.map(renderCard).join("\n\n");

  const body = `
  <section class="hero">
    <div class="wrap">
      <span class="eyebrow">콘텐츠</span>
      <h1>AI를 쓰고, 만들고, 가르치며 기록합니다.</h1>
      <p class="lead">새로운 도구 소식보다 실제 업무와 사업에 적용해본 방법을 중심으로 정리합니다.</p>
    </div>
  </section>

  <section class="section" aria-labelledby="board-h">
    <div class="wrap">
      <h2 id="board-h" class="visually-hidden">전체 콘텐츠</h2>
      <div class="content-filter" role="group" aria-label="카테고리 필터">
        ${filterButtons}
      </div>
      <div class="grid grid--3 mt-9" id="content-grid">
${cards}
      </div>
    </div>
  </section>
`;
  return pageShell({
    title: "콘텐츠 — 배제협 · JerryBay",
    description: "AI를 쓰고, 만들고, 가르치며 기록한 실무 노트, 강의, 언론 인터뷰 아카이브.",
    current: "/insights/",
    body,
  });
}

function buildDetail(post) {
  const externalLine = post.external_url
    ? `        <p><a href="${post.external_url}" target="_blank" rel="noopener noreferrer">관련 자료 보기 ↗</a></p>\n`
    : "";
  const body = `
  <section class="hero">
    <div class="wrap">
      <span class="eyebrow">${escapeHtml(post.category)}</span>
      <h1>${escapeHtml(post.title)}</h1>
      <p class="dim">${formatDate(post.date)}</p>
    </div>
  </section>

  <section class="section" aria-labelledby="post-h">
    <div class="wrap">
      <h2 id="post-h" class="visually-hidden">본문</h2>
${renderBody(post.body)}
${externalLine}      <div class="btn-row">
        <a class="btn btn--secondary" href="/insights/">← 콘텐츠 목록으로</a>
      </div>
    </div>
  </section>
`;
  return pageShell({
    title: `${post.title} — 배제협 · JerryBay`,
    description: post.summary,
    current: "/insights/",
    body,
  });
}

// --- run ---------------------------------------------------------------

const posts = loadPosts();
if (posts.length < 3) {
  console.error(`Need at least 3 seed posts in content/posts/, found ${posts.length}.`);
  process.exit(1);
}

mkdirSync(INSIGHTS_DIR, { recursive: true });
const written = [];

// Clean up stale generated detail directories before regenerating, so a
// removed/renamed post doesn't leave an orphaned page behind.
const currentSlugs = new Set(posts.filter((p) => p.hasDetail).map((p) => p.slug));
if (existsSync(INSIGHTS_DIR)) {
  for (const entry of readdirSync(INSIGHTS_DIR, { withFileTypes: true })) {
    if (!entry.isDirectory()) continue;
    const detailFile = join(INSIGHTS_DIR, entry.name, "index.html");
    if (!currentSlugs.has(entry.name) && existsSync(detailFile)) {
      const contents = readFileSync(detailFile, "utf8");
      if (contents.includes(GENERATED_MARK)) {
        rmSync(join(INSIGHTS_DIR, entry.name), { recursive: true, force: true });
        console.log(`removed stale: insights/${entry.name}/`);
      }
    }
  }
}

const indexPath = join(INSIGHTS_DIR, "index.html");
writeFileSync(indexPath, buildIndex(posts), "utf8");
written.push("insights/index.html");

for (const post of posts) {
  if (!post.hasDetail) continue;
  const dir = join(INSIGHTS_DIR, post.slug);
  mkdirSync(dir, { recursive: true });
  const detailPath = join(dir, "index.html");
  writeFileSync(detailPath, buildDetail(post), "utf8");
  written.push(`insights/${post.slug}/index.html`);
}

console.log(`Built ${posts.length} posts (${posts.filter((p) => p.hasDetail).length} detail pages, ${posts.filter((p) => !p.hasDetail).length} external-only).`);
console.log("Files written:");
for (const f of written) console.log(`  ${f}`);
